name: CI
on: [push]

env:
    LIEFLAND_ENVIRONMENT: Tests

jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install composer dependencies
              uses: php-actions/composer@v6
              with:
                  php_version: "8.1"
                  php_extensions: intl
                  command: 'install'
            - name: Post composer-install
              run: |
                  composer run post-install-cmd
            - name: Install node dependencies
              run: |
                  npm ci
                  npm install -g sass
            - name: Run psalm
              run: |
                  composer run lint:psalm
              continue-on-error: true
            - name: Run code-style
              run: |
                  composer run lint:cs
              continue-on-error: true
            - name: Run Unit Tests
              run: |
                  composer run test:unit
            - name: Build System
              run: |
                  composer run build
            - name: Run System Tests
              run: |
                  composer run test:system
            - name: Clean assets
              continue-on-error: true
              run: |
                  composer run clean
            - name: Validate composer.json
              run: |
                  composer validate
