name: Deploy Pages
on:
    push:
        branches:
            - main
env:
    LIEFLAND_ENVIRONMENT: Pages

jobs:
    build:
        concurrency: ci-${{ github.ref }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install dependencies
              uses: php-actions/composer@v6
              with:
                  php_version: "8.1"
                  php_extensions: intl
                  command: 'install'
            - name: Download sass
              run: |
                  npm install -g sass
            - name: Build
              run: |
                  composer run post-install-cmd
                  composer run publish:pages
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4.2.5
              with:
                  branch: www
                  folder: public
